import React from "react";
import type { Metadata } from "next";
import {Plus_Jakarta_Sans } from "next/font/google";
import "./css/globals.css";
import { ThemeModeScript, ThemeProvider } from 'flowbite-react';
import customTheme from "@/utils/theme/custom-theme";

import '../utils/i18n';
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from "./components/shadcn-ui/Default-Ui/toaster";
import { CustomizerContextProvider } from "./context/CustomizerContext";

const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Modernize - Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <ThemeModeScript />
      </head>
      <body className={`${plus_jakarta_sans.className}`}>
      <NextTopLoader />
        <ThemeProvider theme={customTheme}>
          <CustomizerContextProvider>
            {children}
          </CustomizerContextProvider>
        </ThemeProvider>
        <Toaster/>
      </body>
    </html>

  );
}



